[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "snakemake-storage-plugin-orcestra"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=24.3.1,<25"

[pypi-dependencies]

[environments]
dev = ["test", "dev"]
test = ["test", "quality"]

py311 = { features = ["py311", "test"], no-default-feature = true }
py312 = { features = ["py312", "test"], no-default-feature = true }

############################################## DEV ###############################################
[feature.dev.pypi-dependencies]
snakemake_storage_plugin_orcestra = { path = ".", editable = true }

[feature.dev.dependencies]
ipython = "*"
ipykernel = "*"
jupyterlab = "*"

############################################## PYTHON ###############################################

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

############################################## TEST ################################################
[feature.test.pypi-dependencies]
snakemake_storage_plugin_orcestra = { path = ".", editable = true }

[feature.test.dependencies]
pytest = "*"

############################################## QUALITY ###############################################
# Quality includes linting, type checking, and formatting
[feature.quality.dependencies]
ruff = ">=0.4.8"
mypy = ">=1.13.0,<2"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "--config", "config/ruff.toml", "check", "src"]
ruff-check.description = "Run ruff check"

ruff-format.cmd = ["ruff", "--config", "config/ruff.toml", "format", "src"]
ruff-format.description = "Run ruff format, run check first"

type-check.cmd = ["mypy", "--config-file", "config/mypy.ini", "src"]
type-check.inputs = ["config/mypy.ini", "src"]
type-check.description = "Run mypy type check."

qc.depends-on = ["ruff-format", "ruff-check", "type-check"]
qc.description = "Quality check: ruff & mypy"
